service:
  name: notebook-back
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    NODE_ENV: production
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}


functions:
  graphql:
    handler: src/main.graphqlHandler
    events:
      - http:
          method: get
          path: graphql
          cors: true
      - http:
          method: post
          path: graphql
          cors: true
